/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ISupplyChainInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptTransfer"
      | "initiateTransfer"
      | "mintProduct"
      | "nonces"
      | "registerBatch"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BatchRegistered"
      | "ProductMinted"
      | "TransferAccepted"
      | "TransferInitiated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptTransfer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initiateTransfer",
    values: [BigNumberish, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mintProduct",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "nonces", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "registerBatch",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initiateTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintProduct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nonces", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerBatch",
    data: BytesLike
  ): Result;
}

export namespace BatchRegisteredEvent {
  export type InputTuple = [
    batchId: BigNumberish,
    manufacturer: AddressLike,
    maxUnits: BigNumberish,
    stake: BigNumberish
  ];
  export type OutputTuple = [
    batchId: bigint,
    manufacturer: string,
    maxUnits: bigint,
    stake: bigint
  ];
  export interface OutputObject {
    batchId: bigint;
    manufacturer: string;
    maxUnits: bigint;
    stake: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProductMintedEvent {
  export type InputTuple = [
    productId: BigNumberish,
    batchId: BigNumberish,
    owner: AddressLike,
    metadataHash: BytesLike
  ];
  export type OutputTuple = [
    productId: bigint,
    batchId: bigint,
    owner: string,
    metadataHash: string
  ];
  export interface OutputObject {
    productId: bigint;
    batchId: bigint;
    owner: string;
    metadataHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferAcceptedEvent {
  export type InputTuple = [
    productId: BigNumberish,
    from: AddressLike,
    to: AddressLike
  ];
  export type OutputTuple = [productId: bigint, from: string, to: string];
  export interface OutputObject {
    productId: bigint;
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferInitiatedEvent {
  export type InputTuple = [
    productId: BigNumberish,
    from: AddressLike,
    to: AddressLike,
    locationHash: BytesLike
  ];
  export type OutputTuple = [
    productId: bigint,
    from: string,
    to: string,
    locationHash: string
  ];
  export interface OutputObject {
    productId: bigint;
    from: string;
    to: string;
    locationHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ISupplyChain extends BaseContract {
  connect(runner?: ContractRunner | null): ISupplyChain;
  waitForDeployment(): Promise<this>;

  interface: ISupplyChainInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptTransfer: TypedContractMethod<
    [productId: BigNumberish],
    [void],
    "nonpayable"
  >;

  initiateTransfer: TypedContractMethod<
    [productId: BigNumberish, to: AddressLike, locationHash: BytesLike],
    [void],
    "nonpayable"
  >;

  mintProduct: TypedContractMethod<
    [productId: BigNumberish, batchId: BigNumberish, metadataHash: BytesLike],
    [void],
    "nonpayable"
  >;

  nonces: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  registerBatch: TypedContractMethod<
    [batchId: BigNumberish, maxUnits: BigNumberish],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptTransfer"
  ): TypedContractMethod<[productId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "initiateTransfer"
  ): TypedContractMethod<
    [productId: BigNumberish, to: AddressLike, locationHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mintProduct"
  ): TypedContractMethod<
    [productId: BigNumberish, batchId: BigNumberish, metadataHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nonces"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerBatch"
  ): TypedContractMethod<
    [batchId: BigNumberish, maxUnits: BigNumberish],
    [void],
    "payable"
  >;

  getEvent(
    key: "BatchRegistered"
  ): TypedContractEvent<
    BatchRegisteredEvent.InputTuple,
    BatchRegisteredEvent.OutputTuple,
    BatchRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ProductMinted"
  ): TypedContractEvent<
    ProductMintedEvent.InputTuple,
    ProductMintedEvent.OutputTuple,
    ProductMintedEvent.OutputObject
  >;
  getEvent(
    key: "TransferAccepted"
  ): TypedContractEvent<
    TransferAcceptedEvent.InputTuple,
    TransferAcceptedEvent.OutputTuple,
    TransferAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "TransferInitiated"
  ): TypedContractEvent<
    TransferInitiatedEvent.InputTuple,
    TransferInitiatedEvent.OutputTuple,
    TransferInitiatedEvent.OutputObject
  >;

  filters: {
    "BatchRegistered(uint256,address,uint256,uint256)": TypedContractEvent<
      BatchRegisteredEvent.InputTuple,
      BatchRegisteredEvent.OutputTuple,
      BatchRegisteredEvent.OutputObject
    >;
    BatchRegistered: TypedContractEvent<
      BatchRegisteredEvent.InputTuple,
      BatchRegisteredEvent.OutputTuple,
      BatchRegisteredEvent.OutputObject
    >;

    "ProductMinted(uint256,uint256,address,bytes32)": TypedContractEvent<
      ProductMintedEvent.InputTuple,
      ProductMintedEvent.OutputTuple,
      ProductMintedEvent.OutputObject
    >;
    ProductMinted: TypedContractEvent<
      ProductMintedEvent.InputTuple,
      ProductMintedEvent.OutputTuple,
      ProductMintedEvent.OutputObject
    >;

    "TransferAccepted(uint256,address,address)": TypedContractEvent<
      TransferAcceptedEvent.InputTuple,
      TransferAcceptedEvent.OutputTuple,
      TransferAcceptedEvent.OutputObject
    >;
    TransferAccepted: TypedContractEvent<
      TransferAcceptedEvent.InputTuple,
      TransferAcceptedEvent.OutputTuple,
      TransferAcceptedEvent.OutputObject
    >;

    "TransferInitiated(uint256,address,address,bytes32)": TypedContractEvent<
      TransferInitiatedEvent.InputTuple,
      TransferInitiatedEvent.OutputTuple,
      TransferInitiatedEvent.OutputObject
    >;
    TransferInitiated: TypedContractEvent<
      TransferInitiatedEvent.InputTuple,
      TransferInitiatedEvent.OutputTuple,
      TransferInitiatedEvent.OutputObject
    >;
  };
}
