/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ISupplyChainInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptTransfer"
      | "approveRelayer"
      | "claimRefund"
      | "executeMetaTx"
      | "getBatchMetadata"
      | "getBatchProductCount"
      | "getBatchStatus"
      | "initiateTransfer"
      | "isDisputeActive"
      | "mintProduct"
      | "nonces"
      | "raiseDispute"
      | "registerBatch"
      | "resolveDispute"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BatchRegistered"
      | "BatchStatusChanged"
      | "DisputeRaised"
      | "DisputeResolved"
      | "MetaTxExecuted"
      | "ProductMinted"
      | "ProvenanceRecorded"
      | "RelayerApproved"
      | "TransferAccepted"
      | "TransferInitiated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptTransfer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approveRelayer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRefund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeMetaTx",
    values: [
      AddressLike,
      BigNumberish,
      AddressLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getBatchMetadata",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBatchProductCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBatchStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initiateTransfer",
    values: [BigNumberish, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isDisputeActive",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintProduct",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "nonces", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "raiseDispute",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerBatch",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveRelayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeMetaTx",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBatchMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBatchProductCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBatchStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initiateTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isDisputeActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintProduct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nonces", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "raiseDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
}

export namespace BatchRegisteredEvent {
  export type InputTuple = [
    batchId: BigNumberish,
    manufacturer: AddressLike,
    maxUnits: BigNumberish,
    stake: BigNumberish
  ];
  export type OutputTuple = [
    batchId: bigint,
    manufacturer: string,
    maxUnits: bigint,
    stake: bigint
  ];
  export interface OutputObject {
    batchId: bigint;
    manufacturer: string;
    maxUnits: bigint;
    stake: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BatchStatusChangedEvent {
  export type InputTuple = [
    batchId: BigNumberish,
    status: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    batchId: bigint,
    status: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    batchId: bigint;
    status: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeRaisedEvent {
  export type InputTuple = [
    productId: BigNumberish,
    disputer: AddressLike,
    reason: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    productId: bigint,
    disputer: string,
    reason: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    productId: bigint;
    disputer: string;
    reason: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [
    productId: BigNumberish,
    winner: AddressLike,
    slashedAmount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    productId: bigint,
    winner: string,
    slashedAmount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    productId: bigint;
    winner: string;
    slashedAmount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MetaTxExecutedEvent {
  export type InputTuple = [
    relayer: AddressLike,
    user: AddressLike,
    nonce: BigNumberish
  ];
  export type OutputTuple = [relayer: string, user: string, nonce: bigint];
  export interface OutputObject {
    relayer: string;
    user: string;
    nonce: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProductMintedEvent {
  export type InputTuple = [
    productId: BigNumberish,
    batchId: BigNumberish,
    owner: AddressLike,
    metadataHash: BytesLike
  ];
  export type OutputTuple = [
    productId: bigint,
    batchId: bigint,
    owner: string,
    metadataHash: string
  ];
  export interface OutputObject {
    productId: bigint;
    batchId: bigint;
    owner: string;
    metadataHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProvenanceRecordedEvent {
  export type InputTuple = [
    productId: BigNumberish,
    handler: AddressLike,
    locationHash: BytesLike,
    action: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    productId: bigint,
    handler: string,
    locationHash: string,
    action: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    productId: bigint;
    handler: string;
    locationHash: string;
    action: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RelayerApprovedEvent {
  export type InputTuple = [relayer: AddressLike, approved: boolean];
  export type OutputTuple = [relayer: string, approved: boolean];
  export interface OutputObject {
    relayer: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferAcceptedEvent {
  export type InputTuple = [
    productId: BigNumberish,
    from: AddressLike,
    to: AddressLike
  ];
  export type OutputTuple = [productId: bigint, from: string, to: string];
  export interface OutputObject {
    productId: bigint;
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferInitiatedEvent {
  export type InputTuple = [
    productId: BigNumberish,
    from: AddressLike,
    to: AddressLike,
    locationHash: BytesLike
  ];
  export type OutputTuple = [
    productId: bigint,
    from: string,
    to: string,
    locationHash: string
  ];
  export interface OutputObject {
    productId: bigint;
    from: string;
    to: string;
    locationHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ISupplyChain extends BaseContract {
  connect(runner?: ContractRunner | null): ISupplyChain;
  waitForDeployment(): Promise<this>;

  interface: ISupplyChainInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptTransfer: TypedContractMethod<
    [productId: BigNumberish],
    [void],
    "nonpayable"
  >;

  approveRelayer: TypedContractMethod<
    [relayer: AddressLike],
    [void],
    "nonpayable"
  >;

  claimRefund: TypedContractMethod<
    [productId: BigNumberish],
    [void],
    "nonpayable"
  >;

  executeMetaTx: TypedContractMethod<
    [
      user: AddressLike,
      productId: BigNumberish,
      to: AddressLike,
      locationHash: BytesLike,
      nonce: BigNumberish,
      deadline: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getBatchMetadata: TypedContractMethod<
    [batchId: BigNumberish],
    [
      [string, bigint, bigint, bigint, string] & {
        manufacturer: string;
        maxUnits: bigint;
        minted: bigint;
        stake: bigint;
        status: string;
      }
    ],
    "view"
  >;

  getBatchProductCount: TypedContractMethod<
    [batchId: BigNumberish],
    [bigint],
    "view"
  >;

  getBatchStatus: TypedContractMethod<
    [batchId: BigNumberish],
    [string],
    "view"
  >;

  initiateTransfer: TypedContractMethod<
    [productId: BigNumberish, to: AddressLike, locationHash: BytesLike],
    [void],
    "nonpayable"
  >;

  isDisputeActive: TypedContractMethod<
    [productId: BigNumberish],
    [boolean],
    "view"
  >;

  mintProduct: TypedContractMethod<
    [productId: BigNumberish, batchId: BigNumberish, metadataHash: BytesLike],
    [void],
    "nonpayable"
  >;

  nonces: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  raiseDispute: TypedContractMethod<
    [productId: BigNumberish, reasonHash: BytesLike],
    [void],
    "nonpayable"
  >;

  registerBatch: TypedContractMethod<
    [batchId: BigNumberish, maxUnits: BigNumberish],
    [void],
    "payable"
  >;

  resolveDispute: TypedContractMethod<
    [productId: BigNumberish, winner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptTransfer"
  ): TypedContractMethod<[productId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "approveRelayer"
  ): TypedContractMethod<[relayer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimRefund"
  ): TypedContractMethod<[productId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeMetaTx"
  ): TypedContractMethod<
    [
      user: AddressLike,
      productId: BigNumberish,
      to: AddressLike,
      locationHash: BytesLike,
      nonce: BigNumberish,
      deadline: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBatchMetadata"
  ): TypedContractMethod<
    [batchId: BigNumberish],
    [
      [string, bigint, bigint, bigint, string] & {
        manufacturer: string;
        maxUnits: bigint;
        minted: bigint;
        stake: bigint;
        status: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBatchProductCount"
  ): TypedContractMethod<[batchId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBatchStatus"
  ): TypedContractMethod<[batchId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "initiateTransfer"
  ): TypedContractMethod<
    [productId: BigNumberish, to: AddressLike, locationHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isDisputeActive"
  ): TypedContractMethod<[productId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "mintProduct"
  ): TypedContractMethod<
    [productId: BigNumberish, batchId: BigNumberish, metadataHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nonces"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "raiseDispute"
  ): TypedContractMethod<
    [productId: BigNumberish, reasonHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerBatch"
  ): TypedContractMethod<
    [batchId: BigNumberish, maxUnits: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [productId: BigNumberish, winner: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BatchRegistered"
  ): TypedContractEvent<
    BatchRegisteredEvent.InputTuple,
    BatchRegisteredEvent.OutputTuple,
    BatchRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "BatchStatusChanged"
  ): TypedContractEvent<
    BatchStatusChangedEvent.InputTuple,
    BatchStatusChangedEvent.OutputTuple,
    BatchStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeRaised"
  ): TypedContractEvent<
    DisputeRaisedEvent.InputTuple,
    DisputeRaisedEvent.OutputTuple,
    DisputeRaisedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "MetaTxExecuted"
  ): TypedContractEvent<
    MetaTxExecutedEvent.InputTuple,
    MetaTxExecutedEvent.OutputTuple,
    MetaTxExecutedEvent.OutputObject
  >;
  getEvent(
    key: "ProductMinted"
  ): TypedContractEvent<
    ProductMintedEvent.InputTuple,
    ProductMintedEvent.OutputTuple,
    ProductMintedEvent.OutputObject
  >;
  getEvent(
    key: "ProvenanceRecorded"
  ): TypedContractEvent<
    ProvenanceRecordedEvent.InputTuple,
    ProvenanceRecordedEvent.OutputTuple,
    ProvenanceRecordedEvent.OutputObject
  >;
  getEvent(
    key: "RelayerApproved"
  ): TypedContractEvent<
    RelayerApprovedEvent.InputTuple,
    RelayerApprovedEvent.OutputTuple,
    RelayerApprovedEvent.OutputObject
  >;
  getEvent(
    key: "TransferAccepted"
  ): TypedContractEvent<
    TransferAcceptedEvent.InputTuple,
    TransferAcceptedEvent.OutputTuple,
    TransferAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "TransferInitiated"
  ): TypedContractEvent<
    TransferInitiatedEvent.InputTuple,
    TransferInitiatedEvent.OutputTuple,
    TransferInitiatedEvent.OutputObject
  >;

  filters: {
    "BatchRegistered(uint256,address,uint256,uint256)": TypedContractEvent<
      BatchRegisteredEvent.InputTuple,
      BatchRegisteredEvent.OutputTuple,
      BatchRegisteredEvent.OutputObject
    >;
    BatchRegistered: TypedContractEvent<
      BatchRegisteredEvent.InputTuple,
      BatchRegisteredEvent.OutputTuple,
      BatchRegisteredEvent.OutputObject
    >;

    "BatchStatusChanged(uint256,string,uint256)": TypedContractEvent<
      BatchStatusChangedEvent.InputTuple,
      BatchStatusChangedEvent.OutputTuple,
      BatchStatusChangedEvent.OutputObject
    >;
    BatchStatusChanged: TypedContractEvent<
      BatchStatusChangedEvent.InputTuple,
      BatchStatusChangedEvent.OutputTuple,
      BatchStatusChangedEvent.OutputObject
    >;

    "DisputeRaised(uint256,address,string,uint256)": TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;
    DisputeRaised: TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;

    "DisputeResolved(uint256,address,uint256,uint256)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "MetaTxExecuted(address,address,uint256)": TypedContractEvent<
      MetaTxExecutedEvent.InputTuple,
      MetaTxExecutedEvent.OutputTuple,
      MetaTxExecutedEvent.OutputObject
    >;
    MetaTxExecuted: TypedContractEvent<
      MetaTxExecutedEvent.InputTuple,
      MetaTxExecutedEvent.OutputTuple,
      MetaTxExecutedEvent.OutputObject
    >;

    "ProductMinted(uint256,uint256,address,bytes32)": TypedContractEvent<
      ProductMintedEvent.InputTuple,
      ProductMintedEvent.OutputTuple,
      ProductMintedEvent.OutputObject
    >;
    ProductMinted: TypedContractEvent<
      ProductMintedEvent.InputTuple,
      ProductMintedEvent.OutputTuple,
      ProductMintedEvent.OutputObject
    >;

    "ProvenanceRecorded(uint256,address,bytes32,string,uint256)": TypedContractEvent<
      ProvenanceRecordedEvent.InputTuple,
      ProvenanceRecordedEvent.OutputTuple,
      ProvenanceRecordedEvent.OutputObject
    >;
    ProvenanceRecorded: TypedContractEvent<
      ProvenanceRecordedEvent.InputTuple,
      ProvenanceRecordedEvent.OutputTuple,
      ProvenanceRecordedEvent.OutputObject
    >;

    "RelayerApproved(address,bool)": TypedContractEvent<
      RelayerApprovedEvent.InputTuple,
      RelayerApprovedEvent.OutputTuple,
      RelayerApprovedEvent.OutputObject
    >;
    RelayerApproved: TypedContractEvent<
      RelayerApprovedEvent.InputTuple,
      RelayerApprovedEvent.OutputTuple,
      RelayerApprovedEvent.OutputObject
    >;

    "TransferAccepted(uint256,address,address)": TypedContractEvent<
      TransferAcceptedEvent.InputTuple,
      TransferAcceptedEvent.OutputTuple,
      TransferAcceptedEvent.OutputObject
    >;
    TransferAccepted: TypedContractEvent<
      TransferAcceptedEvent.InputTuple,
      TransferAcceptedEvent.OutputTuple,
      TransferAcceptedEvent.OutputObject
    >;

    "TransferInitiated(uint256,address,address,bytes32)": TypedContractEvent<
      TransferInitiatedEvent.InputTuple,
      TransferInitiatedEvent.OutputTuple,
      TransferInitiatedEvent.OutputObject
    >;
    TransferInitiated: TypedContractEvent<
      TransferInitiatedEvent.InputTuple,
      TransferInitiatedEvent.OutputTuple,
      TransferInitiatedEvent.OutputObject
    >;
  };
}
